FROM debian:buster
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get -y install wget

RUN apt-get -y install php7.3 php-mysql php-fpm php-pdo php-gd php-cli php-mbstring php-json php-iconv php-mysqli php-phar php-xml
WORKDIR /var/www/
RUN wget https://files.phpmyadmin.net/phpMyAdmin/5.0.1/phpMyAdmin-5.0.1-english.tar.gz
RUN tar -xf phpMyAdmin-5.0.1-english.tar.gz && rm -rf phpMyAdmin-5.0.1-english.tar.gz
RUN mv phpMyAdmin-5.0.1-english phpmyadmin
COPY ./conf/config.inc.php phpmyadmin

COPY ./conf/ /var/www/
RUN cp -a www.conf /etc/php/7.3/fpm/pool.d/www.conf

RUN chown -R www-data:www-data *
RUN chmod -R 755 /var/www/*

EXPOSE 9000
ENTRYPOINT ["/var/www/init_w.sh"]
CMD ["/usr/sbin/php-fpm7.3", "--nodaemonize"]
