FROM alpine:3.12
RUN apk update && apk upgrade
RUN apk add nginx openssl php-gd php-xml
RUN openssl req -x509 -nodes -days 365 -subj "/C=RF/ST=RT/L=Kazan/O=42School/OU=21Kazan/CN=aantonin" -newkey rsa:2048 -keyout /etc/ssl/nginx-selfsigned.key -out /etc/ssl/nginx-selfsigned.crt;
RUN mkdir -p /run/nginx
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]
